// apps/web/examples/PDFViewerApp/index.tsx
import { useEffect, useState } from "react";
import { usePDFSlick } from "@pdfslick/react";
import Toolbar from "./Toolbar";
import Thumbsbar from "./Thumbsbar";

type PDFViewerAppProps = {
  pdfFilePath: string;
};

export default function PDFViewerApp({ pdfFilePath }: PDFViewerAppProps) {
  const [isThumbsbarOpen, setIsThumbsbarOpen] = useState(false);
  const {
    isDocumentLoaded,
    viewerRef,
    thumbsRef,
    usePDFSlickStore,
    PDFSlickViewer,
  } = usePDFSlick(pdfFilePath, {
    onProgress: ({ loaded, total }) => {
      console.log(loaded, total)
    }
  });

  useEffect(() => {
    if (isDocumentLoaded) {
      setIsThumbsbarOpen(true);
    }
  }, [isDocumentLoaded]);

  return (
    <div className="absolute inset-0 bg-slate-200/70 flex flex-col pdfSlick">
      <Toolbar {...{ usePDFSlickStore, setIsThumbsbarOpen, isThumbsbarOpen }} />
      <div className="flex-1 flex">
        <Thumbsbar {...{ thumbsRef, usePDFSlickStore, isThumbsbarOpen }} />

        <div className="flex-1 relative h-full">
          <PDFSlickViewer {...{ viewerRef, usePDFSlickStore }} />
        </div>
      </div>
    </div>
  );
}

// apps/solidweb/src/examples/PDFViewerApp/index.tsx
import { Component, createSignal } from "solid-js";
import { usePDFSlick } from "@pdfslick/solid";
import Thumbsbar from "./Thumbsbar";
import Toolbar from "./Toolbar";

type PDFViewerAppProps = {
  pdfFilePath: string;
};

const PDFViewerApp: Component<PDFViewerAppProps> = ({ pdfFilePath }) => {
  const {
    viewerRef,
    thumbsRef,
    pdfSlickStore: store,
    PDFSlickViewer,
  } = usePDFSlick(pdfFilePath, {
    onProgress: ({ total, loaded }) => {
      console.log(loaded, total)
    },
  });
  const [isThumbsbarOpen, setIsThumbsbarOpen] = createSignal(true);

  return (
    <div class="absolute inset-0 bg-slate-200/70 flex flex-col pdfSlick">
      <Toolbar {...{ store, setIsThumbsbarOpen, isThumbsbarOpen }} />
      <div class="flex-1 flex">
        <Thumbsbar {...{ store, isThumbsbarOpen, thumbsRef }} />

        <div class="flex-1 relative h-full">
          <PDFSlickViewer {...{ store, viewerRef }} />
        </div>
      </div>
    </div>
  );
};

export default PDFViewerApp;
