// apps/solidweb/src/examples/PDFViewerApp/Thumbsbar/Attachments.tsx
import type { PDFSlickState } from "@pdfslick/solid";
import { type Component, For } from "solid-js";

type AttachmentsProps = {
  store: PDFSlickState;
  show: boolean;
};

type AttachmentButtonProps = {
  store: PDFSlickState;
  filename: string;
  content: Uint8Array;
};

const AttachmentButton: Component<AttachmentButtonProps> = (props) => {
  let ref!: HTMLButtonElement;

  return (
    <button
      ref={ref}
      class="w-full box-border rounded-sm text-left hover:text-slate-900 p-1 hover:bg-slate-200"
      onClick={() =>
        props.store.pdfSlick?.openOrDownloadData(
          props.content,
          props.filename
        )
      }
    >
      {props.filename}
    </button>
  );
};

const Attachments: Component<AttachmentsProps> = (props) => {
  return (
    <div
      class="overflow-auto absolute inset-0"
      classList={{ invisible: !props.show }}
    >
      <div class="p-2 text-slate-700 text-sm">
        <For each={Array.from(props.store.attachments.values())}>
          {({ filename, content }) => (
            <AttachmentButton {...{ store: props.store, filename, content }} />
          )}
        </For>
      </div>
    </div>
  );
};

export default Attachments;

// apps/web/examples/PDFViewerApp/Thumbsbar/Attachments.tsx
import { FC, useRef, MutableRefObject } from "react";
import { type TUsePDFSlickStore } from "@pdfslick/react";
import clsx from "clsx";

type AttachmentsProps = {
  usePDFSlickStore: TUsePDFSlickStore;
  show: boolean;
};

type AttachmentButtonProps = {
  usePDFSlickStore: TUsePDFSlickStore;
  filename: string;
  content: Uint8Array;
};

const AttachmentButton: FC<AttachmentButtonProps> = ({
  usePDFSlickStore,
  filename,
  content,
}) => {
  const pdfSlick = usePDFSlickStore((s) => s.pdfSlick);
  const ref = useRef() as MutableRefObject<HTMLButtonElement>;

  return (
    <button
      ref={ref}
      className="w-full box-border rounded text-left hover:text-slate-900 p-1 hover:bg-slate-200"
      onClick={() =>
        pdfSlick?.openOrDownloadData(content, filename)
      }
    >
      {filename}
    </button>
  );
};

const Attachments = ({ usePDFSlickStore, show }: AttachmentsProps) => {
  const attachments = usePDFSlickStore((s) => s.attachments);

  return (
    <div
      className={clsx("overflow-auto absolute inset-0", { invisible: !show })}
    >
      <div className="p-2 text-slate-700 text-sm">
        {Array.from(attachments.entries()).map(
          ([key, { filename, content }]) => (
            <AttachmentButton
              key={key}
              {...{ usePDFSlickStore, filename, content }}
            />
          )
        )}
      </div>
    </div>
  );
};

export default Attachments;
