// apps/web/examples/PDFViewerApp/Toolbar/FreetextMenu.tsx
import { Fragment } from "react";
import { Menu, Transition } from "@headlessui/react";
import { VscChevronDown, VscCaseSensitive } from "react-icons/vsc";
import { AnnotationEditorType, AnnotationEditorParamsType } from "pdfjs-dist";
import { default as colors, colorNames, colorStrengths } from "../colors";

import type { TUsePDFSlickStore } from "@pdfslick/react";

type FreetextMenuProps = {
  usePDFSlickStore: TUsePDFSlickStore;
};

const FreetextMenu = ({ usePDFSlickStore }: FreetextMenuProps) => {
  const annotationEditorMode = usePDFSlickStore((s) => s.annotationEditorMode);
  const pdfSlick = usePDFSlickStore((s) => s.pdfSlick);
  const isFreetextMode = annotationEditorMode === AnnotationEditorType.FREETEXT;

  return (
    <div
      className={`flex items-center group rounded-sm ${
        isFreetextMode ? "bg-blue-100" : "hover:bg-slate-200/50"
      }`}
    >
      <button
        className={`enabled:hover:text-black text-slate-600 p-0.5 disabled:text-slate-300 rounded-sm transition-all group relative focus:border-blue-400 focus:ring-0 focus:shadow outline-none border border-transparent`}
        onClick={() => {
          const mode = isFreetextMode
            ? AnnotationEditorType.NONE
            : AnnotationEditorType.FREETEXT;
          pdfSlick?.setAnnotationEditorMode(mode);
        }}
      >
        <VscCaseSensitive className="w-5 h-5" />
      </button>

      <Menu as="div" className="text-xs relative h-6">
        <Menu.Button
          disabled={!pdfSlick}
          className={`h-6 enabled:group-hover:hover:bg-slate-200 enabled:hover:text-black text-slate-500 disabled:text-slate-300 rounded-sm transition-all focus:border-blue-400 focus:ring-0 focus:shadow outline-none border border-transparent`}
        >
          <div className="p-0.5">
            <VscChevronDown className="w-3 h-3" />
          </div>
        </Menu.Button>
        <Transition
          as={Fragment}
          enter="transition ease-out duration-100"
          enterFrom="transform opacity-0 scale-95"
          enterTo="transform opacity-100 scale-100"
          leave="transition ease-in duration-75"
          leaveFrom="transform opacity-100 scale-100"
          leaveTo="transform opacity-0 scale-95"
        >
          <Menu.Items className="absolute right-0 z-30 mt-1 origin-top-right rounded-sm text-left bg-white divide-y divide-slate-200 shadow-lg ring-1 ring-black/5 focus:outline-none">
            <div className="flex flex-col space-y-0.5 p-2">
              <div className="text-sm font-medium text-gray-900 py-1">
                Color
              </div>
              {colorStrengths.map((s) => (
                <div className="flex space-x-0.5" key={s}>
                  {colorNames.map((name) => (
                    // <Menu.Item key={`${name}-${s}`}>
                    <button
                      key={`${name}-${s}`}
                      className="p-2 rounded-full border border-slate-200 hover:border-slate-400 hover:shadow-sm focus:ring-blue-500"
                      style={{
                        backgroundColor: colors[name][s],
                      }}
                      onClick={() => {
                        pdfSlick?.setAnnotationEditorMode(
                          AnnotationEditorType.FREETEXT
                        );
                        pdfSlick?.setAnnotationEditorParams([
                          {
                            type: AnnotationEditorParamsType.FREETEXT_COLOR,
                            value: colors[name][s],
                          },
                        ]);
                      }}
                    />
                    // </Menu.Item>
                  ))}
                </div>
              ))}
            </div>

            <div className="p-2 flex flex-col">
              <div className="py-1 flex space-x-2 items-center">
                <label
                  htmlFor="innkThickness"
                  className="text-sm w-20 font-medium text-gray-900"
                >
                  Font Size
                </label>
                <div className="w-full flex flex-1 items-center">
                  <input
                    className="w-full h-1.5 bg-slate-200 rounded-lg appearance-none cursor-pointer"
                    defaultValue={1}
                    type="range"
                    min={12}
                    max={100}
                    onChange={(e) => {
                      pdfSlick?.setAnnotationEditorParams([
                        {
                          type: AnnotationEditorParamsType.FREETEXT_SIZE,
                          value: +e.target.value,
                        },
                      ]);
                    }}
                  />
                </div>
              </div>
            </div>
          </Menu.Items>
        </Transition>
      </Menu>
    </div>
  );
};

export default FreetextMenu;

// apps/svelteweb/src/lib/PDFViewerApp/Toolbar/FreeTextMenu.svelte
<script lang="ts">
	import { AnnotationEditorType, AnnotationEditorParamsType } from 'pdfjs-dist';
	import { clsx } from 'clsx';
	import { scale } from 'svelte/transition';
	import { quintOut, quintIn } from 'svelte/easing';
	import { Menu, MenuButton, MenuItems } from '@rgossiaux/svelte-headlessui';
	import { pdfSlickStore } from '$lib/store';
	import { default as colors, colorStrengths, colorNames } from '$lib/colors';

	let isFreetextMode = false;
	let fontSize = 12;

	$: isFreetextMode = $pdfSlickStore?.annotationEditorMode === AnnotationEditorType.FREETEXT;

	$: {
		if ($pdfSlickStore?.pdfSlick && fontSize) {
			$pdfSlickStore?.pdfSlick?.setAnnotationEditorParams([
				{
					type: AnnotationEditorParamsType.FREETEXT_SIZE,
					value: fontSize
				}
			]);
		}
	}
</script>

<div
	class={clsx(`flex items-center group rounded-sm`, {
		'bg-blue-100': isFreetextMode,
		'hover:bg-slate-200/50': !isFreetextMode
	})}
>
	<button
		class={`inline-flex enabled:hover:text-black text-slate-600 p-0.5 disabled:text-slate-300 rounded-sm transition-all group relative focus:border-blue-400 focus:ring-0 focus:shadow outline-none border border-transparent`}
		on:click={() => {
			const mode = isFreetextMode ? AnnotationEditorType.NONE : AnnotationEditorType.FREETEXT;
			$pdfSlickStore?.pdfSlick?.setAnnotationEditorMode(mode);
		}}
	>
		<iconify-icon height={20} icon="codicon:case-sensitive" />
	</button>

	<Menu class="relative" let:open>
		<MenuButton
			disabled={!$pdfSlickStore?.pdfSlick}
			class="h-6 enabled:group-hover:hover:bg-slate-200 enabled:hover:text-black text-slate-500 disabled:text-slate-300 rounded-sm transition-all focus:border-blue-400 focus:ring-0 focus:shadow outline-none border border-transparent"
			on:click={(e) => {
				e.preventDefault();
				e.stopPropagation();
			}}
		>
			<div class="inline-flex p-0.5">
				<iconify-icon height={12} icon="codicon:chevron-down" />
			</div>
		</MenuButton>

		{#if open}
			<div
				in:scale={{ duration: 100, delay: 0, opacity: 0.75, start: 0.95, easing: quintOut }}
				out:scale={{ duration: 75, delay: 0, opacity: 0, start: 0.95, easing: quintIn }}
			>
				<MenuItems
					static
					class="absolute right-0 z-30 mt-2 origin-top-right rounded-sm text-left bg-white divide-y divide-slate-200 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none"
					role="menu"
					aria-orientation="vertical"
					tabindex={-1}
				>
					<div class="flex flex-col space-y-1 p-2">
						<div class="text-sm font-medium text-gray-900 py-1">Color</div>
						{#each colorStrengths as s}
							<div class="flex space-x-1">
								{#each colorNames as name}
									<button
										class="p-2 cursor-pointer block rounded-full origin-center border border-transparent hover:scale-125 hover:border-blue-300 focus:ring-0 focus:outline-none focus:scale-125 focus:border-blue-300"
										style={`background-color: ${colors[name][s]}`}
										on:click={(e) => {
											e.preventDefault();
											e.stopPropagation();

											$pdfSlickStore?.pdfSlick?.setAnnotationEditorMode(
												AnnotationEditorType.FREETEXT
											);
											$pdfSlickStore?.pdfSlick?.setAnnotationEditorParams([
												{
													type: AnnotationEditorParamsType.FREETEXT_COLOR,
													value: colors[name][s]
												}
											]);
										}}
									/>
								{/each}
							</div>
						{/each}
					</div>

					<div class="p-2 flex flex-col">
						<div class="py-1 flex space-x-2 items-center">
							<label for="fontSize" class="text-sm w-20 font-medium text-gray-900">
								Font Size
							</label>
							<div class="w-full flex flex-1 items-center">
								<input
									class="w-full h-1.5 bg-slate-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-700"
									bind:value={fontSize}
									id="fontSize"
									type="range"
									min={12}
									max={100}
								/>
							</div>
						</div>
					</div>
				</MenuItems>
			</div>
		{/if}
	</Menu>
</div>
