// packages/solid/PDFSlickViewer.tsx
/** @jsxImportSource solid-js */
import { createEffect, createSignal } from "solid-js";
import { createElementSize } from "@solid-primitives/resize-observer";
import type { PDFSlickState } from "@pdfslick/core";

export type PDFSlickViewerProps = {
  viewerRef: (instance: HTMLElement) => void;
  store: PDFSlickState;
  class?: string;
};

export default function PDFSlickViewer(props: PDFSlickViewerProps) {
  const [resizeRef, setResizeRef] = createSignal<HTMLElement>();

  const size = createElementSize(resizeRef);
  createEffect(() => {
    if (size.width && size.height) {
      if (
        props.store.pdfSlick &&
        (props.store.scaleValue === "auto" ||
          props.store.scaleValue === "page-fit" ||
          props.store.scaleValue === "page-width")
      ) {
        props.store.pdfSlick.viewer.currentScaleValue = props.store.scaleValue;
      }
      props.store.pdfSlick?.viewer.update();
    }
  });

  return (
    <div
      ref={(el) => {
        props.viewerRef(el);
        setResizeRef(el);
      }}
      id="viewerContainer"
      class={`pdfSlickContainer ${props.class ?? ""}`}
      style={{
        "position": "absolute",
        "inset": 0,
        "overflow": "auto"
      }}
    >
      <div id="viewer" class="pdfSlickViewer pdfViewer" />
    </div>
  );
}

// packages/react/PDFSlickViewer.tsx
import { useMeasure, useDebounce } from "react-use";
import type { TUsePDFSlickStore } from "@pdfslick/react";

export type PDFSlickViewerProps = {
  viewerRef: (instance: HTMLElement) => void;
  usePDFSlickStore: TUsePDFSlickStore;
  className?: string;
};

export default function PDFSlickViewer({
  usePDFSlickStore,
  viewerRef,
  className,
}: PDFSlickViewerProps) {
  const pdfSlick = usePDFSlickStore((s) => s.pdfSlick);
  const scaleValue = usePDFSlickStore((s) => s.scaleValue);

  const [resizeRef, { width }] = useMeasure<HTMLDivElement>();

  useDebounce(
    () => {
      if (width) {
        if (
          pdfSlick &&
          (scaleValue === "auto" ||
            scaleValue === "page-fit" ||
            scaleValue === "page-width")
        ) {
          pdfSlick.viewer.currentScaleValue = scaleValue;
        }
        pdfSlick?.viewer.update();
      }
    },
    0,
    [width]
  );

  return (
    <div
      ref={(el) => {
        viewerRef(el!);
        resizeRef(el!);
      }}
      id="viewerContainer"
      className={`pdfSlickContainer ${className ?? ""}`}
      style={{
        position: "absolute",
        inset: 0,
        overflow: "auto"
      }}
    >
      <div id="viewer" className="pdfSlickViewer pdfViewer" />
    </div>
  );
}
